### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by Otherwa** [Otherwa/Vela-patrak_v_1.0#10]
Login page

**Comment by Otherwa** [comment]
[timetable_Data.xls](https://github.com/Otherwa/Vela-patrak_v_1.0/files/9394322/timetable_Data.xls)
[Timetable_screenShots.docx](https://github.com/Otherwa/Vela-patrak_v_1.0/files/9394321/Timetable_screenShots.docx)

**Comment by devashishSule** [comment]
Registration works on server but not on local host for some unaware reasons

**Comment by Otherwa** [comment]
Ha laudu local madhe table nahi
